This is makeindex, version 2.17 [TeX Live 2026/dev] (kpathsea + Thai support).
Scanning style file ./template_cnam.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file template_cnam.acn....done (2 entries accepted, 0 rejected).
Sorting entries....done (2 comparisons).
Generating output file template_cnam.acr....done (6 lines written, 0 warnings).
Output written in template_cnam.acr.
Transcript written in template_cnam.alg.
